#!/usr/bin/env python3
"""Optional OFFLINE Chromium DOM checks, not an HTTP/CSP/deployment test.

Requires Playwright + Chromium, not needed by the collector or viewer.
  python -m pip install playwright
  python -m playwright install chromium
  python tests/browser_smoke.py

CHROME_BIN can select an installed Chromium executable. The harness serves the
shipped HTML from a routed, non-existent origin under a repository subpath, so
no request leaves the browser, and mocks fetch with synthetic club datasets. It
removes the CSP only in this test document to permit injecting scripts; shipped
files retain CSP. Screenshots are optional:
  python tests/browser_smoke.py --screenshots /tmp/club-preview
"""
from pathlib import Path
import argparse
import copy
import json
import os
import re
import shutil
import sys
import tempfile
from urllib.parse import quote
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / 'site'
sys.path.insert(0, str(Path(__file__).resolve().parent))
import multiclub_fixtures as f  # noqa: E402

BASE = 'http://viewer.test/EA-FC-pro-club-tracker/'
# Ignores AbortSignal on purpose: a late answer for a club that is no longer
# selected must be dropped by the viewer itself.
MOCK_FETCH = '''({files, delays}) => {
  window.__requests = [];
  window.fetch = async url => {
    const path = new URL(url, document.baseURI).pathname.split('/EA-FC-pro-club-tracker/')[1];
    window.__requests.push(path);
    if (delays[path]) await new Promise(resolve => setTimeout(resolve, delays[path]));
    if (!(path in files)) return {ok: false, status: 404, json: async () => { throw new Error('not JSON'); }};
    return {ok: true, status: 200, json: async () => structuredClone(files[path])};
  };
}'''
CAPTURE_DOWNLOAD = '''() => {
  window.__csv = null; window.__download = null;
  URL.createObjectURL = blob => {blob.text().then(text => window.__csv = text); return 'blob:offline-test';};
  URL.revokeObjectURL = () => {};
  HTMLAnchorElement.prototype.click = function() {window.__download = this.download;};
}'''


def single(payload):
    """A one-club published site for a ready-made dataset."""
    club = payload.get('club') or payload['config']
    return {'data/clubs.json': {'schema_version': 1, 'default_club_id': club['club_id'], 'clubs': [club]},
            f"data/clubs/{club['club_id']}/index.json": payload}


def built_site():
    """The three synthetic clubs, generated by the real collector and site builder."""
    with tempfile.TemporaryDirectory() as directory:
        f.publish(Path(directory))
        data = Path(directory) / 'site' / 'data'
        return {'data/' + path.relative_to(data).as_posix(): json.loads(path.read_bytes())
                for path in data.rglob('*.json')}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--screenshots', type=Path)
    args = parser.parse_args()
    demo = json.loads((SITE / 'demo.json').read_text(encoding='utf-8'))
    # Never depend on or modify a user's real generated archive for the empty test.
    empty = copy.deepcopy(demo)
    empty.update(matches=[], collection={'status': 'not_requested', 'message': 'Synthetic empty fixture.'})
    empty['club'].update(club_name='Empty test club')
    clubs = built_site()
    html = (SITE / 'index.html').read_text(encoding='utf-8')
    html = re.sub(r'<meta http-equiv="Content-Security-Policy"[^>]*>', '', html)
    html = re.sub(r'<script[^>]*src="[^"]+"[^>]*></script>', '', html)
    html = re.sub(r'<link rel="stylesheet"[^>]*>', '', html)
    checks = []

    def check(condition, label):
        if not condition:
            raise AssertionError(label)
        checks.append(label)
        print('PASS:', label)

    with sync_playwright() as pw:
        executable = os.environ.get('CHROME_BIN') or shutil.which('chromium')
        browser = pw.chromium.launch(headless=True, executable_path=executable,
                                     args=['--no-sandbox'])
        errors = []

        def load(files, query='', width=1440, delays=None, context=None, remembered=None, settle='phase !== "loading"'):
            context = context or browser.new_context(viewport={'width': width, 'height': 1080}, device_scale_factor=1)
            page = context.new_page()
            page.on('pageerror', lambda error: errors.append(str(error)))
            page.route('**/*', lambda route: route.fulfill(status=200, content_type='text/html', body=html)
                       if route.request.url.split('?')[0] == BASE else route.abort())
            page.goto(BASE + query)
            page.add_style_tag(content=(SITE / 'assets/style.css').read_text(encoding='utf-8'))
            if remembered is not None:
                page.evaluate('value => localStorage.setItem("dubsfc-tracker.club", value)', remembered)
            page.evaluate(MOCK_FETCH, {'files': files, 'delays': delays or {}})
            for script in ('stats.js', 'clubs.js', 'app.js'):
                page.add_script_tag(content=(SITE / 'assets' / script).read_text(encoding='utf-8'))
            page.wait_for_function(settle)
            return page

        def text(page, selector):
            return page.locator(selector).inner_text()

        def choose(page, club_id, settle=True):
            page.select_option('#club-select', club_id)
            if settle:
                page.wait_for_function('id => phase !== "loading" && club.club_id === id', arg=club_id)

        def settled(page):
            """Loaded cleanly: no leftover loading state and no error notice."""
            return page.evaluate('phase') == 'ready' and not page.locator('#load-error').is_visible() and not page.locator('#collector-health').is_visible()

        def summary(page):
            return (text(page, '#club-name'), text(page, '#match-count'), text(page, '#record'), text(page, '#goals'))

        def table(page, stat):
            """{player name: (cell text, highlighted as column maximum)}."""
            rows = {}
            for row in page.locator('#player-body tr').all():
                cell = row.locator(f'[data-stat="{stat}"]')
                rows[row.locator('.player-name').inner_text()] = (cell.inner_text(), 'column-best' in (cell.get_attribute('class') or ''))
            return rows

        def export_view(page):
            page.evaluate(CAPTURE_DOWNLOAD)
            page.locator('#export-view').click()
            page.wait_for_function('typeof window.__csv === "string"')
            return page.evaluate('[window.__csv, window.__download]')

        # ---- Existing single-dataset behaviour, on the synthetic demo ----
        page = load({'demo.json': demo}, '?demo=1')
        check(page.locator('#player-body tr').count() == 5, 'demo renders 5 synthetic players')
        check(page.locator('#demo-banner').is_visible(), 'synthetic payload cannot look like a live archive')
        check(page.evaluate('window.__requests') == ['demo.json'], 'demo mode reads only its own synthetic file')
        check(not page.locator('#club-picker').is_visible() and not page.locator('#export').is_visible(), 'demo has no club selector or archive export')
        check(page.get_by_role('tab').count() == 5, 'exactly five metric tabs')
        check(page.title() == 'DubsFC Tracker', 'page title uses requested brand')
        check('DubsFC Tracker' in page.locator('.brand').inner_text(), 'wordmark updated')
        check('Event coverage' not in page.locator('body').inner_text(), 'no event coverage in viewer')
        check('Know what the numbers mean' not in page.locator('body').inner_text(), 'explanatory block removed')
        check('Every match you save' not in page.locator('body').inner_text(), 'hero slogan removed')
        overview_head = page.locator('#player-head').text_content()
        check('Successful dribbles' in overview_head and 'Tackles won' in overview_head, 'overview includes successful dribbles and tackles won')
        check('Shots' not in overview_head and 'On target' not in overview_head, 'overview omits shooting columns')

        if args.screenshots:
            args.screenshots.mkdir(parents=True, exist_ok=True)
            page.screenshot(path=str(args.screenshots / 'overview-desktop.png'), full_page=True)

        for view, expected in [('Shooting', 'On target'), ('Passing', 'Through balls'), ('Dribbling', 'Skill-move beats'), ('Defending', 'Ball recovered (dispossessions)')]:
            tab = page.get_by_role('tab', name=view, exact=True); tab.click()
            check(tab.get_attribute('aria-selected') == 'true' and expected in page.locator('#player-head').text_content(), f'{view} tab changes columns and active state')
            if args.screenshots:
                page.screenshot(path=str(args.screenshots / (view.lower() + '-desktop.png')), full_page=True)
                page.locator('#players').screenshot(path=str(args.screenshots / (view.lower() + '-table.png')))
        check(not re.search(r'cross', page.locator('#player-head').text_content(), re.I), 'no crossing column')
        page.get_by_role('tab', name='Passing', exact=True).click()
        before = page.locator('[data-stat="pass_rate"]').all_inner_texts()
        page.locator('#per-match').check()
        check(page.locator('[data-stat="pass_rate"]').all_inner_texts() == before, 'per-match toggle does not change percentages')
        check('Forward %' not in page.locator('#player-head').inner_text() and 'Long %' not in page.locator('#player-head').inner_text(), 'unrequested pass columns removed')
        page.locator('#player-search').fill('creator')
        check(page.locator('#player-body tr').count() == 1 and 'Creator 10' in page.locator('#player-body').inner_text(), 'player search filters visible rows')
        # Mock only the DOM download click, capture the actual Blob generated.
        exported, _ = export_view(page)
        check('Creator 10' in exported and 'Runner 7' not in exported and 'through_balls_completed' in exported, 'view CSV respects player search and selected category')
        page.locator('#player-search').fill('')
        page.locator('#per-match').uncheck()
        page.locator('#competition').select_option('friendlyMatch')
        page.get_by_role('tab', name='Dribbling', exact=True).click()
        check(page.locator('#match-count').inner_text() == '2', 'competition filter selects demo friendlies')
        check(all(value == '—' for value in page.locator('[data-stat="dribble_beats"]').all_inner_texts()), 'missing friendly event data stays unavailable')
        page.locator('#competition').select_option('all')
        page.locator('#period').select_option('last5')
        check(page.locator('#match-count').inner_text() == '5', 'last-5 archive filter works')
        page.locator('#period').select_option('all')
        page.locator('.match-item > summary').first.click()
        page.wait_for_selector('.match-group')
        check(page.locator('.match-item').first.locator('.match-group').count() == 5, 'expanded match provides all five statistic groups')
        page.locator('.match-item').first.locator('[data-group="passing"] > summary').click()
        check('Forward %' not in page.locator('.match-item').first.locator('[data-group="passing"]').text_content(), 'match detail omits forward and long columns')
        page.get_by_role('tab', name='Overview', exact=True).focus()
        page.get_by_role('tab', name='Overview', exact=True).click()
        page.keyboard.press('ArrowRight')
        check(page.get_by_role('tab', name='Shooting', exact=True).get_attribute('aria-selected') == 'true', 'keyboard arrow navigation selects next tab')

        # Collapse detail and reset viewport for visual inspection.
        page.locator('.match-item > summary').first.click()
        for width in (390, 320):
            page.set_viewport_size({'width': width, 'height': 844})
            check(page.evaluate('document.documentElement.scrollWidth <= innerWidth'), f'{width}px mobile has no page-level horizontal overflow')
        page.set_viewport_size({'width': 390, 'height': 844})
        page.get_by_role('tab', name='Dribbling', exact=True).click()
        if args.screenshots:
            page.screenshot(path=str(args.screenshots / 'dribbling-mobile.png'), full_page=True)
        page.close()

        page = load(single(empty))
        check('No matches archived yet for Empty test club' in page.locator('#player-body').inner_text(), 'real empty archive is not replaced by demo data')
        check(not page.locator('#demo-banner').is_visible(), 'empty production dataset is not labelled synthetic')
        check(not page.locator('#collector-health').is_visible(), 'no build-only health messages shown')
        check(not page.locator('#club-picker').is_visible(), 'a single configured club needs no selector')
        page.close()

        error_fixture = copy.deepcopy(empty)
        error_fixture['collection'] = {'status': 'error', 'needs_attention': True, 'message': 'Simulated API failure'}
        page = load(single(error_fixture))
        check(page.locator('#collector-health').is_visible() and 'Simulated API failure' in page.locator('#health-text').inner_text(), 'real failures remain visible')
        page.close()

        unsafe = copy.deepcopy(demo)
        unsafe['matches'][0]['players'][0]['name'] = '<img src=x onerror="window.pwned=true">'
        unsafe['club']['club_name'] = '<img src=x onerror="window.pwned=true"> FC'
        page = load(single(unsafe))
        check(page.locator('#player-body img').count() == 0 and '<img' in page.locator('#player-body').inner_text(), 'untrusted player names render as text, not HTML')
        check(page.locator('main img').count() == 0 and '<img' in text(page, '#club-name') and not page.evaluate('window.pwned'), 'untrusted club names render as text, not HTML')
        page.close()
        legacy = copy.deepcopy(demo); legacy['schema_version'] = 1
        legacy['config'] = legacy.pop('club')
        for match in legacy['matches']:
            for player in match['players']:
                for key in ['forward_passes_completed', 'forward_pass_attempts', 'dribble_beats', 'interceptions']:
                    player.pop(key, None)
        page = load(single(legacy))
        page.get_by_role('tab', name='Dribbling', exact=True).click()
        check(all(value == '—' for value in page.locator('[data-stat="dribble_beats"]').all_inner_texts()), 'old viewer payloads tolerate missing newly added fields')
        check(page.locator('#mapping-note').count() == 0, 'community-mapping banner is removed, including for legacy schema payloads')
        page.close()

        # ---- Several clubs: first visit ----
        page = load(clubs)
        check(summary(page) == ('Alpha United', '3', '1 · 1 · 1', '4 / 4'), 'first visit opens the default club with its own record and goals')
        check(page.evaluate('window.__requests') == ['data/clubs.json', 'data/clubs/100/index.json'], 'only the selected club dataset is loaded')
        check(page.locator('#club-picker').is_visible() and page.locator('#club-select').input_value() == '100'
              and page.locator('#club-select option').all_inner_texts() == ['Alpha United', 'Beta Town', 'Gamma Empty'], 'selector lists every configured club')
        check(page.locator('#club-picker').text_content().startswith('Club') and 'CLUB 100' in text(page, '#edition'), 'selector is labelled and the club ID is shown')
        check(page.title() == 'DubsFC Tracker' and 'DubsFC Tracker' in text(page, '.brand'), 'project branding is kept with several clubs')
        check(table(page, 'goals') == {'Alpha Anchor': ('3', True), 'Shared Striker': ('1', False)}, 'Alpha totals and goal highlight come from Alpha matches only')
        check(table(page, 'appearances') == {'Alpha Anchor': ('3', True), 'Shared Striker': ('3', True)}, 'tied column maxima are both highlighted')
        check(page.evaluate('getComputedStyle(document.querySelector("#record .record-win")).color !== getComputedStyle(document.querySelector("#record .record-loss")).color')
              and page.locator('#goals .goals-for').inner_text() == '4' and page.locator('#goals .goals-against').inner_text() == '4', 'win/loss and goals for/against colours are kept')
        check(text(page, '#match-caption') == '2 players in these matches' and text(page, '#matches-label') == '3 matches · most recent first', 'archived match and player counts belong to Alpha')
        derby = page.locator('.match-item[data-match-id="9001"]')
        check([derby.locator('.result').inner_text(), derby.locator('.opponent').inner_text(), derby.locator('.score').inner_text()] == ['W', 'vs Beta Town', '3:1'], 'derby is a 3:1 win against Beta for Alpha')
        derby.locator('summary').first.click()
        page.wait_for_selector('.match-item[data-match-id="9001"] .match-group')
        check(derby.locator('[data-group="overview"] tbody th').all_inner_texts() == ['Shared Striker', 'Alpha Anchor'], 'expanded derby lists Alpha players only')
        check(text(page, '#archive-stamp').startswith('Alpha United archive changed') and not page.locator('#collector-health').is_visible(), 'last-update line names the club')
        check(page.locator('#export').get_attribute('href') == 'data/clubs/100/player_matches_100.csv'
              and page.locator('#export').get_attribute('download') == 'alpha-united-100-player-matches.csv', 'all-match export points at Alpha with its name and ID')
        exported, name = export_view(page)
        check(name == 'alpha-united-100-overview-totals.csv' and exported.replace('﻿', '').startswith('club_id,club_name,player_id')
              and '100,Alpha United,501,Alpha Anchor,3,totals,3,' in exported, 'view export is named for and labelled with Alpha')
        if args.screenshots:
            page.screenshot(path=str(args.screenshots / 'clubs-alpha-desktop.png'), full_page=True)

        # ---- Switching: filters, summaries, tables, details, exports ----
        page.get_by_role('tab', name='Shooting', exact=True).click()
        page.locator('#player-search').fill('anchor')
        page.locator('#competition').select_option('playoffMatch')
        page.locator('#period').select_option('last5')
        check(text(page, '#match-count') == '1' and page.locator('#player-body tr').count() == 1, 'filters narrow Alpha before switching')
        choose(page, f.BETA)
        check(summary(page) == ('Beta Town', '2', '1 · 0 · 1', '5 / 3'), 'switching updates the name, archived matches, record and goals')
        check('club=200' in page.url and page.url.startswith(BASE), 'switching writes a shareable ?club= address under the same subpath')
        check(page.evaluate('window.__requests') == ['data/clubs.json', 'data/clubs/100/index.json', 'data/clubs/200/index.json'], 'a switch loads only the newly selected dataset')
        check(page.locator('#player-search').input_value() == '' and page.locator('#competition').input_value() == 'all', 'filters that select nothing in the new club are reset')
        check(page.locator('#period').input_value() == 'last5' and page.get_by_role('tab', name='Shooting', exact=True).get_attribute('aria-selected') == 'true', 'club-independent period and the current tab are kept')
        check(table(page, 'goals') == {'Shared Striker': ('3', True), 'Beta Runner': ('2', False), 'Beta Keeper': ('0', False)}, 'goal highlight is recalculated among Beta players')
        check(table(page, 'appearances') == {'Shared Striker': ('1', False), 'Beta Runner': ('2', True), 'Beta Keeper': ('2', True)}, 'a player in both clubs keeps separate appearances per club')
        body = text(page, 'main')
        check('Alpha Anchor' not in body and 'Opponent X' not in body and 'Opponent Y' not in body, 'no Alpha player or opponent remains after switching')
        check(page.locator('.match-item[open]').count() == 0, 'expanded match details from the previous club are closed')
        derby = page.locator('.match-item[data-match-id="9001"]')
        check([derby.locator('.result').inner_text(), derby.locator('.opponent').inner_text(), derby.locator('.score').inner_text()] == ['L', 'vs Alpha United', '1:3'], 'the same derby is a 1:3 loss against Alpha for Beta')
        derby.locator('summary').first.click()
        page.wait_for_selector('.match-item[data-match-id="9001"] .match-group')
        check(derby.locator('[data-group="overview"] tbody th').all_inner_texts() == ['Beta Keeper', 'Beta Runner'], 'expanded derby lists Beta players only')
        check(page.locator('#export').get_attribute('href') == 'data/clubs/200/player_matches_200.csv'
              and page.locator('#export').get_attribute('download') == 'beta-town-200-player-matches.csv', 'all-match export follows the selected club')
        exported, name = export_view(page)
        check(name == 'beta-town-200-shooting-totals.csv' and '200,Beta Town,500,Shared Striker,1,totals,3,' in exported and 'Alpha' not in exported, 'view export contains Beta rows only')
        check(text(page, '#archive-stamp').startswith('Beta Town archive changed') and 'CLUB 200' in text(page, '#edition'), 'last-update line and ID follow the selected club')
        if args.screenshots:
            page.screenshot(path=str(args.screenshots / 'clubs-beta-desktop.png'), full_page=True)
        page.locator('#player-search').fill('striker')
        choose(page, f.ALPHA)
        check(page.locator('#player-search').input_value() == 'striker' and table(page, 'goals') == {'Shared Striker': ('1', True)}, 'a search that still matches is kept; the highlight covers displayed players only')
        page.locator('#player-search').fill('')
        check(table(page, 'goals') == {'Alpha Anchor': ('3', True), 'Shared Striker': ('1', False)}, 'switching back restores Alpha numbers, not a merged total')

        # ---- Empty club ----
        choose(page, f.GAMMA)
        check(summary(page) == ('Gamma Empty', '0', '—', '—'), 'a club without matches shows an empty summary')
        check('No matches archived yet for Gamma Empty' in text(page, '#player-body') and 'No matches archived yet for Gamma Empty' in text(page, '#match-list'), 'empty club has a proper empty state in both panels')
        body = text(page, 'main')
        check(all(name not in body for name in ['Shared Striker', 'Alpha Anchor', 'Beta Runner', 'Opponent']), 'an empty club never shows another club data')
        check(page.locator('#export-view').is_disabled() and not page.locator('#demo-banner').is_visible() and text(page, '#archive-stamp') == 'Gamma Empty archive is empty', 'empty club has no view export and is not labelled synthetic')
        for width in (390, 320):
            page.set_viewport_size({'width': width, 'height': 844})
            check(page.evaluate('document.documentElement.scrollWidth <= innerWidth'), f'{width}px mobile with the club selector has no horizontal overflow')
        if args.screenshots:
            choose(page, f.BETA)
            page.screenshot(path=str(args.screenshots / 'clubs-beta-mobile.png'), full_page=True)
        context = page.context
        page.close()

        # ---- Remembered and address-bar selection ----
        choose(load(clubs, context=context), f.BETA)
        page = load(clubs, context=context)
        check(summary(page)[:2] == ('Beta Town', '2') and 'club=' not in page.url, 'the last selected club is remembered on a later visit')
        page = load(clubs, '?club=100', context=context)
        check(summary(page)[:2] == ('Alpha United', '3') and page.locator('#club-select').input_value() == '100', 'a valid ?club= address wins over the remembered club')
        check(page.evaluate('window.__requests') == ['data/clubs.json', 'data/clubs/100/index.json'], 'the remembered club is not fetched when the address names another')
        check(page.evaluate('localStorage.getItem("dubsfc-tracker.club")') == '200', 'opening a shared link does not overwrite the remembered club')
        context.close()
        page = load(clubs, '?club=200')
        check(summary(page) == ('Beta Town', '2', '1 · 0 · 1', '5 / 3'), 'a shared ?club=200 link opens that club directly')
        page.close()
        page = load(clubs, remembered='300')
        check(summary(page)[:2] == ('Gamma Empty', '0'), 'a remembered club without matches opens its empty state, not the default')
        page.close()

        # ---- Invalid selections ----
        for value in ['999', '../200', '200/../100', 'data/clubs/200', '200/index.json', 'https://example.invalid/x', '<script>', ' 200', '0200']:
            page = load(clubs, '?club=' + quote(value, safe=''), remembered=value)
            check(summary(page)[:2] == ('Alpha United', '3') and page.evaluate('window.__requests') == ['data/clubs.json', 'data/clubs/100/index.json'],
                  f'invalid selection {value!r} falls back to the default and fetches no other path')
            page.close()
        page = load(clubs, '?club=999', remembered='200')
        check(summary(page)[:2] == ('Beta Town', '2'), 'an invalid address falls back to a valid remembered club')
        page.close()

        # ---- Rapid switching and late answers ----
        slow = {'data/clubs/200/index.json': 700}
        page = load(clubs, delays=slow)
        choose(page, f.BETA, settle=False)
        check(text(page, '#club-name') == 'Beta Town' and text(page, '#match-count') == '0' and 'Loading Beta Town' in text(page, '#player-body')
              and 'Alpha Anchor' not in text(page, 'main'), 'while a club loads, the previous club numbers are already gone')
        choose(page, f.GAMMA)
        page.wait_for_timeout(1100)
        check(summary(page) == ('Gamma Empty', '0', '—', '—') and 'Beta Runner' not in text(page, 'main') and page.evaluate('club.club_id') == '300'
              and settled(page) and 'No matches archived yet for Gamma Empty' in text(page, '#player-body'),
              'a late answer for an abandoned club does not replace the selected empty club')
        choose(page, f.BETA, settle=False)
        choose(page, f.ALPHA)
        page.wait_for_timeout(1100)
        check(summary(page) == ('Alpha United', '3', '1 · 1 · 1', '4 / 4') and table(page, 'goals') == {'Alpha Anchor': ('3', True), 'Shared Striker': ('1', False)}
              and page.locator('#club-select').input_value() == '100' and 'club=100' in page.url and settled(page), 'rapid switching ends on the last selection with its own data')
        for club_id in (f.BETA, f.GAMMA, f.ALPHA, f.GAMMA, f.BETA):
            choose(page, club_id, settle=False)
        page.wait_for_function('phase === "ready" && club.club_id === "200"')
        page.wait_for_timeout(900)
        check(summary(page) == ('Beta Town', '2', '1 · 0 · 1', '5 / 3') and 'Alpha Anchor' not in text(page, 'main') and settled(page), 'five quick switches settle on the final club only')
        page.close()

        # ---- Per-club status ----
        status = copy.deepcopy(clubs)
        status['data/clubs/200/index.json']['collection'] = {'status': 'error', 'needs_attention': True, 'message': 'Simulated Beta failure',
                                                            'last_api_attempt_at': '2026-09-30T10:00:00+00:00'}
        page = load(status)
        check(not page.locator('#collector-health').is_visible(), 'a healthy club shows no collector warning')
        choose(page, f.BETA)
        check(page.locator('#collector-health').is_visible() and 'Simulated Beta failure' in text(page, '#health-text') and 'API attempt' in text(page, '#freshness'), 'collection status and last attempt belong to the selected club')
        check(summary(page)[:2] == ('Beta Town', '2'), 'a collection error still shows that club archived matches')
        choose(page, f.ALPHA)
        check(not page.locator('#collector-health').is_visible() and text(page, '#health-text') == '', 'the warning does not follow the viewer to another club')
        page.close()

        # ---- Wrong or missing datasets are never substituted ----
        mixed = copy.deepcopy(clubs)
        mixed['data/clubs/200/index.json'] = copy.deepcopy(clubs['data/clubs/100/index.json'])
        page = load(mixed, '?club=200')
        check(text(page, '#club-name') == 'Beta Town' and 'does not belong to Beta Town' in text(page, '#load-error') and text(page, '#match-count') == '0'
              and 'Alpha Anchor' not in text(page, 'main'), 'a dataset belonging to another club is refused, not displayed')
        choose(page, f.ALPHA)
        check(summary(page)[:2] == ('Alpha United', '3') and not page.locator('#load-error').is_visible() and not page.locator('#collector-health').is_visible(), 'the error clears when a healthy club is selected')
        page.close()
        missing = {name: value for name, value in clubs.items() if name != 'data/clubs/300/index.json'}
        page = load(missing)
        choose(page, f.GAMMA)
        check('HTTP 404' in text(page, '#load-error') and 'could not be loaded' in text(page, '#player-body') and 'Shared Striker' not in text(page, 'main')
              and not page.locator('#export').is_visible(), 'a missing dataset shows an error, never the previous club')
        page.close()
        unconfigured = {'data/clubs.json': {'schema_version': 1, 'default_club_id': '', 'clubs': []}}
        page = load(unconfigured, '?club=100')
        check('No club configured yet' in text(page, '#player-body') and not page.locator('#club-picker').is_visible()
              and page.evaluate('window.__requests') == ['data/clubs.json'], 'no configured club is a setup state without further requests')
        page.close()
        page = load({}, settle='phase === "failed"')
        check('HTTP 404' in text(page, '#load-error') and page.locator('#status-pill').text_content() == 'Data unavailable', 'a missing catalog is reported')
        page.close()

        check(not errors, 'no JavaScript page errors: ' + repr(errors))
        browser.close()
    print(f'\n{len(checks)} offline DOM checks passed. HTTP, CSP and live EA access are NOT tested.')


if __name__ == '__main__':
    main()
